# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1103, 880)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # for Q5
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(450, 530, 511, 291))
        self.groupBox_7.setObjectName("groupBox_7")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_16.setGeometry(QtCore.QRect(20, 30, 200, 40))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_17.setGeometry(QtCore.QRect(20, 80, 200, 40))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_18.setGeometry(QtCore.QRect(20, 130, 200, 40))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_19.setGeometry(QtCore.QRect(20, 180, 200, 40))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_20.setGeometry(QtCore.QRect(20, 230, 200, 40))
        self.pushButton_20.setObjectName("pushButton_20")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_7)
        self.graphicsView.setGeometry(QtCore.QRect(260, 40, 171, 171))
        self.graphicsView.setObjectName("graphicsView")
        self.label_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_3.setGeometry(QtCore.QRect(260, 40, 171, 171))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.groupBox_7)
        self.label.setGeometry(QtCore.QRect(256, 241, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_7)
        self.label_2.setGeometry(QtCore.QRect(350, 240, 121, 21))
        self.label_2.setObjectName("label_2")

        # for Q4
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(160, 530, 240, 291))
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_12.setGeometry(QtCore.QRect(20, 40, 200, 40))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_13.setGeometry(QtCore.QRect(20, 100, 200, 40))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_14.setGeometry(QtCore.QRect(20, 160, 200, 40))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_15.setGeometry(QtCore.QRect(20, 220, 200, 40))
        self.pushButton_15.setObjectName("pushButton_15")

        # for Q3
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(840, 20, 240, 480))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 240, 200, 40))
        self.pushButton_11.setObjectName("pushButton_11")

        # for Q2
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(570, 20, 240, 480))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 270, 200, 40))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_10.setGeometry(QtCore.QRect(20, 390, 200, 40))
        self.pushButton_10.setObjectName("pushButton_10")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit.setGeometry(QtCore.QRect(20, 60, 200, 40))
        self.lineEdit.setObjectName("lineEdit")

        # for Q1
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(290, 20, 240, 480))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 40, 200, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 110, 200, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 190, 221, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 80, 200, 40))
        self.pushButton_6.setObjectName("pushButton_6")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(80, 40, 53, 22))
        self.comboBox.setCurrentText("1")
        self.comboBox.setMaxVisibleItems(15)
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 350, 200, 40))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 410, 200, 40))
        self.pushButton_8.setObjectName("pushButton_8")

        # for Load Image
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 240, 480))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(20, 90, 200, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 220, 200, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 340, 200, 40))
        self.pushButton_3.setObjectName("pushButton_3")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1103, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        # for Q5
        self.groupBox_7.setTitle(_translate("MainWindow", "5. VGG19"))
        self.pushButton_16.setText(_translate("MainWindow", "Load Image"))
        self.pushButton_17.setText(_translate("MainWindow", "5.1 Show Augmented Image"))
        self.pushButton_18.setText(_translate("MainWindow", "5.2 Show Model Structure"))
        self.pushButton_19.setText(_translate("MainWindow", "5.3 Show Acc and Loss"))
        self.pushButton_20.setText(_translate("MainWindow", "5.4 Inference"))
        self.label.setText(_translate("MainWindow", "Predicted ="))

        # for Q4
        self.groupBox_6.setTitle(_translate("MainWindow", "4. SIFT"))
        self.pushButton_12.setText(_translate("MainWindow", "Load Image 1"))
        self.pushButton_13.setText(_translate("MainWindow", "Load Image 2"))
        self.pushButton_14.setText(_translate("MainWindow", "4.1 Keypoints"))
        self.pushButton_15.setText(_translate("MainWindow", "4.2 Matched Keypoints"))

        # for Q3
        self.groupBox_5.setTitle(_translate("MainWindow", "3. Stereo Disparity Map"))
        self.pushButton_11.setText(_translate("MainWindow", "3.1 Stereo Disparity Map"))

        # for Q2
        self.groupBox_4.setTitle(_translate("MainWindow", "2.Augmented Reality"))
        self.pushButton_9.setText(_translate("MainWindow", "2.1 Show Words on Board"))
        self.pushButton_10.setText(_translate("MainWindow", "2.2 Show Words Vertically"))

        # for Q1
        self.groupBox_2.setTitle(_translate("MainWindow", "1.Calibration"))
        self.pushButton_4.setText(_translate("MainWindow", "1.1 Find Corners"))
        self.pushButton_5.setText(_translate("MainWindow", "1.2 Find Intrinsic"))
        self.groupBox_3.setTitle(_translate("MainWindow", "1.3 Find Extrinsic"))
        self.pushButton_6.setText(_translate("MainWindow", "1.3 Find Extrinsic"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox.setItemText(14, _translate("MainWindow", "15"))
        self.pushButton_7.setText(_translate("MainWindow", "1.4 Find Distortion"))
        self.pushButton_8.setText(_translate("MainWindow", "1.5 Show Result"))

        # for load Image
        self.groupBox.setTitle(_translate("MainWindow", "Load Image"))
        self.pushButton.setText(_translate("MainWindow", "Load Folder"))
        self.pushButton_2.setText(_translate("MainWindow", "Load Image_L"))
        self.pushButton_3.setText(_translate("MainWindow", "Load Image_R"))
